### ISSUE TITLE
Logo detection pylint error

### ISSUE THREAD

**Issue by ocarlosteixeira** [googleapis/python-vision#100]
how to fix: Instance of 'ImageAnnotatorClient' has no 'logo_detection' member?

**Comment by munkhuushmgl** [comment]
@ocarlosteixeira Hello Thanks for opening issue,


Could you share all your version of python packages and python version?

**Comment by munkhuushmgl** [comment]
Due to inactivity, I am closing this issue. Feel free to reopen this issue.
