### ISSUE TITLE
TextAnnotation doesn't have orientationDegrees

### ISSUE THREAD

**Issue by manycoding** [googleapis/python-vision#156]
REST v1 AnnotateImageResponse  already returns `orientationDegrees` https://cloud.google.com/vision/docs/reference/rest/v1/AnnotateImageResponse#Page but looks like this library proto files  hasn't been updated for a while:
https://github.com/googleapis/googleapis/blob/master/google/cloud/vision/v1/text_annotation.proto#L96
https://github.com/googleapis/googleapis/blob/master/google/cloud/vision/v1p4beta1/text_annotation.proto#L98

#### Environment details

  - `google-cloud-vision` version: 2.3.0

#### Steps to reproduce

  1. Send any DOCUMENT_TEXT_DETECTION request to REST \ with this library 
  2. check `Pages`

A similar issue https://github.com/googleapis/python-vision/issues/138

**Comment by manycoding** [comment]
I also see that RPC Reference has `orientation_degrees ` too https://cloud.google.com/vision/docs/reference/rpc/google.cloud.vision.v1#google.cloud.vision.v1.TextAnnotation

**Comment by vinnysenthil** [comment]
Hi @manycoding, a recent update of our reference documentation for the Vision API included fields that are unavailable on the service. We've since updated the documentation to be accurate. Apologies for any trouble caused by this.

**Comment by manycoding** [comment]
@vinnysenthil I am now confused. This ticket https://issuetracker.google.com/issues/35903522 says it's fixed and `orientation_degrees` should be there in the response.
