### ISSUE TITLE
TextDetectionParams does not support all documented fields

### ISSUE THREAD

**Issue by mhucka** [googleapis/python-vision#157]
The current definition of the class `google.cloud.vision_v1.types.TextDetectionParams` does not support all of the parameters that are documented in the Google Cloud Vision API. If possible, it would be good to get the additional parameters supported.

#### Environment details

  - OS type and version: macOS 10.13.6
  - Python version: 3.9.1
  - pip version: 21.0.1
  - `google-cloud-vision` version: 

```
Name: google-cloud-vision
Version: 2.3.1
Summary: Cloud Vision API API client library
Home-page: https://github.com/googleapis/python-vision
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /usr/local/lib/python3.9/site-packages
Requires: google-api-core, proto-plus
Required-by:
```

#### Steps to reproduce

According to the documentation at https://cloud.google.com/vision/docs/reference/rpc/google.cloud.vision.v1#google.cloud.vision.v1.TextDetectionParams, the `TextDetectionParams` object has a number of possible field values. However, the corresponding class in the Python package currently (as of 2.3.1) _only_ has `enable_text_detection_confidence_score`, as can be seen in the documentation at https://googleapis.dev/python/vision/latest/vision_v1/types.html?highlight=textdetection#google.cloud.vision_v1.types.TextDetectionParams and also the source code

#### Code example

This doesn't seem necessary; the issue is pretty clearly evident from both the API docs and the code itself.

#### Stack trace

Not relevant.

**Comment by vinnysenthil** [comment]
Hi @mhucka, thanks for reaching out. A recent update of our reference documentation for the Vision API included fields that are unavailable on the service. We've since updated the documentation to be accurate. Apologies for any trouble caused by this.
