### ISSUE TITLE
Please Document if indeed Raspberry Pi ARMv6 is not supported

### ISSUE THREAD

**Issue by slowrunner** [googleapis/python-vision#18]
I have spent days trying to debug an "illegal instruction" on import google.cloud.vision on a RaspberryPi ARMv6, making sure everything was updated, correct versions, etc. to no avail, and cannot find a statement if or if not Raspberry Pi ARMv6 is supported anywhere on cloud.google.com developer documentation.  There are some two year old frustrated user posts on the net saying "no longer supported" but nothing official anywhere.  Would have been nice under the Linux/Debian tutorials and "Getting Started" stuff.

Since lots of Raspberry Pi with PiCamera users are trying google.cloud.vision, you all could really help them avoid buying the wrong Pi.

If not supported, could you all put  "Note: Raspberry Pi ARMv6 is not supported by google.cloud" in the README.md for python-vision?

**Comment by munkhuushmgl** [comment]
@slowrunner 

`"There is an internal binary at google that does not comply with armv6 processors."`

However, you can use Google Cloud IoT. Core to connect your device to the cloud, and encode your image in base64, publish it as telemetry.

This example might be useful for reference.

https://github.com/GoogleCloudPlatform/google-cloud-iot-arduino/tree/master/examples/complex/esp32/camera

**Comment by slowrunner** [comment]
Thanks for your reply.  Noted.
