### ISSUE TITLE
Feature request: ability to import text_format items

### ISSUE THREAD

**Issue by bschlief** [googleapis/python-vision#199]
**Is your feature request related to a problem? Please describe.**
I have a some `text_format` (as opposed to json or raw protobuf) outputs of AnnotationImageResponse that were output using the the java client: (com.google.cloud:google-cloud-vision:jar:1.100.10)

I'm attempting to ingest those `text_format` files and output Json.

The best approach I've come up with so far is as follows, using `google-cloud-vision==2.4.0`

```python
import io
import sys
from google.cloud import vision_v1, vision
from google.protobuf import text_format, json_format

def parse_text_format_as_json(file_path="path/to/your/file"):
    with io.open(file_path, 'r') as f:
        content = f.read()
        # had to put in allow_unknown_field=True because the java version is able to
        # parse the "type" field in the detectedBreak object, and python can't. 
        proto = vision_v1.types.AnnotateImageResponse()._meta.pb()
        parsed = text_format.Parse(content, proto, allow_unknown_field=True)
        return json_format.MessageToJson(parsed)

if __name__ == "__main__":
    print(parse_text_format_as_json(sys.argv[1]))
``` 

The problem is that the new proto-plus stuff seems to have a way to import from json, but not from text format.

I'd love to have a method on `vision.AnnotateImageResponse.from_text_format` so that I could read these text formatted files like so:

```python
def parse_text_format_as_json(file_path="path/to/your/file"):
    with io.open(file_path, 'r') as f:
        content = f.read()
        parsed = vision.AnnotateImageResponse.from_text_format(content)
        return json_format.MessageToJson(parsed)
```

My alternative solution is above, where I"m reading into the vision_v1 to get the AnnotateImageResponse, then grabbing the protobuf from the `_meta`, which feels a little dirty.

**Comment by telpirion** [comment]
This seems like a proto-plus request rather than a python-vision request. I suggest that you open you issue here:
https://github.com/googleapis/proto-plus-python
