### ISSUE TITLE
Detections with no confidence for TEXT_DETECTION OCR API. 

### ISSUE THREAD

**Issue by sergiuchereches** [googleapis/python-vision#266]
TEXT_DETECTION returns detections with 0.0 confidence. 
e.g 
text_annotations {
  description: "Ang"
  bounding_poly {
    vertices {
      x: 333
      y: 878
    }
    vertices {
      x: 366
      y: 881
    }
    vertices {
      x: 364
      y: 900
    }
    vertices {
      x: 332
      y: 897
    }
  }
}
no confidence is returned and 0.0 might be the default value. 
Is this the expected behaviour? 

also a stack about this:
https://stackoverflow.com/questions/62682707/ocr-confidence-score-from-google-vision-api

**Comment by nicain** [comment]
Hello @sergiuchereches! Can you help me investigate this by providing a minimal, self-containted code snippet that reproduces the behavior?

**Comment by sergiuchereches** [comment]
> Hello @sergiuchereches! Can you help me investigate this by providing a minimal, self-containted code snippet that reproduces the behavior?

Hello, sure! Thank you for your assistance! :) 

from google.cloud import vision
from google.oauth2 import service_account
import cv2

image = cv2.cvtColor(cv2.imread('some_image_with_text.png'), cv2.COLOR_BGR2RGB)
success, encoded_image = cv2.imencode('.png', image)
bytes_im = encoded_image.tobytes()
image = vision.Image(content=bytes_im)
credentials = service_account.Credentials.from_service_account_info(json_credentials)
client = vision.ImageAnnotatorClient(credentials=credentials)
response = client.text_detection(image=image, image_context={"language_hints": None})

**Comment by kweinmeister** [comment]
Please try updating your code as follows to enable the confidence score. You should then see confidence scores in the `full_text_annotation` section of the response:

```python
text_detection_params = vision.TextDetectionParams(enable_text_detection_confidence_score=True)
image_context = vision.ImageContext(text_detection_params=text_detection_params)
response = client.text_detection(image=image, image_context=image_context)
```

**Comment by kweinmeister** [comment]
Hi @sergiuchereches, have you tried this solution yet?

**Comment by sergiuchereches** [comment]
Yes! Your suggestion worked. Thanks for the assistance! :)
