### ISSUE TITLE
AttributeError: partially initialized module 'google.cloud.vision' has no attribute 'ImageAnnotatorClient' (most likely due to a circular import)

### ISSUE THREAD

**Issue by biographie** [googleapis/python-vision#34]
I just installed google-cloud-vision via conda using the following command
conda install google-cloud-vision
and I'm Getting the above error
#### Environment details

  - OS type and version: 
  - Python version: 3.8.5
  - conda version: conda install google-cloud-vision
  - `google-cloud-vision` version: 0.42.0

#### Steps to reproduce

python x.py 
#### Code example
x.py
```python
from google.cloud import vision
client = vision.ImageAnnotatorClient()

AttributeError: module 'google.cloud.vision' has no attribute 'ImageAnnotatorClient'
```

**Comment by munkhuushmgl** [comment]
I was able to run without any problem. it might be problem on your end (might  be duplicate import by looking circular import message).

```
conda config --add channels conda-forge
 7981  [2020-07-28 13:57:42 -0700] conda install google-cloud-vision conda config --add channels conda-forge
 7982  [2020-07-28 13:57:44 -0700] conda install google-cloud-vision conda config --add channels conda-forge
 7983  [2020-07-28 13:57:47 -0700] conda install google-cloud-vision
 7984  [2020-07-28 13:58:43 -0700] ls
 7985  [2020-07-28 13:58:48 -0700] touch x.py
 7986  [2020-07-28 13:58:49 -0700] ls
 7987  [2020-07-28 13:58:55 -0700] code x.py
 7988  [2020-07-28 13:59:15 -0700] python --version
 7989  [2020-07-28 13:59:18 -0700] python x.py
```

**Comment by munkhuushmgl** [comment]
friendly ping

**Comment by munkhuushmgl** [comment]
Due to inactivity, closing this issue. Feel free to reopen if you are still experiencing same issue.

**Comment by bmabir17** [comment]
I think the conda package of google-cloud-vision version: 0.42.0 is not updated with the latest changes in this repo. I faced similar error
`AttributeError: module 'google.cloud.vision' has no attribute 'Image'`

But solved it as follows

```python
            client = vision.ImageAnnotatorClient()
            image = vision.types.Image(content=image_data)
            response = client.text_detection(
                image=image,
                image_context={"language_hints": ["en"]},
            )
```
Now i have found that `types` has been deprecated last fall

**Comment by tillmo** [comment]
Probably, your `x.py` is named `google.py`? This would cause the error.
