### ISSUE TITLE
render_doc_text unncessarily makes the same request three times

### ISSUE THREAD

**Issue by kirchhof** [googleapis/python-vision#357]
**Is your feature request related to a problem? Please describe.**
When calling render_doc_text, it will make the same API request three times. This is slow, causes network overhead, and triples the processing fees for the API request (if not covered within free usage quota). 
https://github.com/googleapis/python-vision/blob/HEAD/samples/snippets/document_text/doctext.py

 **Describe the solution you'd like**
I would like to make the API request only once and then process the response to this request three times. 

 **Describe alternatives you've considered**
None.

 **Additional context**
None.

**Comment by parthea** [comment]
Transferred to https://github.com/GoogleCloudPlatform/python-docs-samples/issues/8543 as the samples have moved to https://github.com/GoogleCloudPlatform/python-docs-samples
