### ISSUE TITLE
face_detection returns empty response while label_detection works

### ISSUE THREAD

**Issue by simonsays1980** [googleapis/python-vision#37]
Over the last two days I am trying out the `face_detection` feature of the `ImageAnnotatorClient`. It always returns an empty list. You can see in the attached picture that it indeed contains a face. 
I then checked the `label_detection` method and this works perfectly and returns a full response. I also tried to send a request using `annotate_image` directly using the `vision.enums.Feature.Type.FACE_DETECTION` feature and get the same result: an empty list. 
Finally I checked the [Vision API online ](https://cloud.google.com/vision/docs/drag-and-drop) and dropped the image there. This works and the face is recognized in a frame as a person. 
So, why is it not working in the `python-vision` library? I checked the code and found in the `decorators.py`file that the special feature methods are added on the fly to the `ImageAnnotatorClient`. Could it be that something there goes wrong? 

I am working on AI Platform Notebooks using a TensorFlow 2.2 Notebook without GPUs. 

Here the code I use: 
```from google.cloud.vision import types
def detect_face(file, max_results=4):
    """Find a face in an image and return its coordinates"""
    client = vision.ImageAnnotatorClient()
    content = file.read()
    image = types.Image(content=content)
    
    # Return the face coordinates
    return client.face_detection(image=image, max_results=max_results).face_annotations
```

Here the code used with `label_detection` (this works):

```
with open('test_image.png', 'rb') as img:
    client = vision.ImageAnnotatorClient()
    content = img.read()
    image = types.Image(content=content)
    
    ret = client.label_detection(image=image)
    ret
```

And here the example using `annotate_image` directly with the `FACE_DETECTION` feature:

```
from google.cloud import vision
from base64 import b64encode
with open('test_image.png', 'rb') as img:
    client = vision.ImageAnnotatorClient()
    content = img.read()
    image = types.Image(content=content)
    
    ret = client.annotate_image({
        'image': {'content': b64encode(content)},
        'features': [{'type': vision.enums.Feature.Type.FACE_DETECTION}],
    })
    ret
```

I appreciate your work. 
![test_image](https://user-images.githubusercontent.com/1795399/90119793-4ef9a480-dd5a-11ea-8b33-952d1e3fe820.png)

**Comment by simonsays1980** [comment]
I tried now to resize my image using `Pillow`:

```
from PIL import Image
im = Image.open("test_image.png")
rgb_im = im.resize((440, 220))
rgb_im = rgb_im.convert('RGB')
rgb_im.save('test_image.png')
```

This worked now with the face_detection. It appears that the size of a head makes a difference (at least I deduce this from the fact that `label_detection` works excellent on the large-size image).

**Comment by munkhuushmgl** [comment]
will take a look.

**Comment by munkhuushmgl** [comment]
@simonsays1980 I was reproduce your issue. I am getting an empty list also using your provided image.
I will log a bug internally.

**Comment by telpirion** [comment]
I will escalate this issue with the Vision team.

**Comment by telpirion** [comment]
Googlers, see 170160669.

**Comment by telpirion** [comment]
We were able to reproduce this internally with the image provided, but we haven't found a systemic cause for this issue. Other faces of the same size work fine.

@simonsays1980 it sounds like you've found a workaround. If you run into the same problem with other images, please reopen this issue.
