### ISSUE TITLE
Vision: custom vocabulary in vision ocr (handwritten text)

### ISSUE THREAD

**Issue by prohit93** [googleapis/python-vision#4]
I would like to pass the keywords that i  expect to be present in the image as an argument to document_text_detection. Just as you can pass the context to speech to text, it would be useful to have something like that here as well.

**Comment by czahedi** [comment]
Hi, I've filed an internal feature request for this, which you can track there / vote on: https://b.corp.google.com/issues/148799831

Thanks :)

**Comment by busunkim96** [comment]
Closing this issue, please follow the link above.
