### ISSUE TITLE
How can i set proxy ?

### ISSUE THREAD

**Issue by wantao666** [googleapis/python-vision#43]
```
client = vision.ImageAnnotatorClient()
        with io.open(path, 'rb') as image_file:
            content = image_file.read()

        image = vision.types.Image(content=content)

        # response = client.text_detection(image=image)
        response = client.document_text_detection(image=image)
```
in china ,these network request can't reach.i set proxy in cmd terminal.but i wan't to set proxy in code.how can i do ?

**Comment by munkhuushmgl** [comment]
SOrry for late response
Have you got a chance to look at this ?

https://cloud.google.com/sdk/docs/proxy-settings

**Comment by munkhuushmgl** [comment]
https://medium.com/google-cloud/accessing-google-cloud-apis-though-a-proxy-fe46658b5f2a

**Comment by munkhuushmgl** [comment]
Due to inactivity, I am closing this issue. Feel free to reopen this issue.
