### ISSUE TITLE
handwritten layer for microgenerator

### ISSUE THREAD

**Issue by arithmetic1728** [googleapis/python-vision#48]
python microgenerator doesn't generate `enums` module, so the handwritten layer no longer works.
https://github.com/googleapis/python-vision/blob/75f1405aedb2416a45064951848b5bbf7a36a1b6/google/cloud/vision_helpers/decorators.py#L26

Example client code generated by python microgenerator: https://github.com/googleapis/python-vision/tree/sijun/google/cloud/vision_v1

This is currently blocking the conversion to use microgenerator.

**Comment by arithmetic1728** [comment]
cc: @busunkim96

**Comment by software-dov** [comment]
I don't think this should be too complicated. The annotated class just needs an explicit reference to the `Feature` enum, and the logic in the decorator needs to change a little to accommodate that.
The definition of `inner` in `_create_single_feature_method` needs to be tweaked a little to be more compliant with the new method surface; there needs to be a `metadata` param as well, and `retry`, `timeout`, and `metadata` need to be keyword only.

**Comment by arithmetic1728** [comment]
@software-dov This is very helpful. Thank you Dov!

**Comment by arithmetic1728** [comment]
This is fixed. Closing the issue.
