### ISSUE TITLE
AutoML Vision: Apple CoreML Version of the classifier does not output a label - Solution?

### ISSUE THREAD

**Issue by tmsm1999** [googleapis/python-vision#49]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Good evening,

For the past few months I have been using Google AutoML Vision to train different Machine Learning Classifiers to perform Single-Label classification. At the moment I am experimenting with those models in order to deploy them in an iOS application.

For every different model I downloaded the CoreML version and tried to run inference on them. For the first one, generated on the 9th of April 2020 everything went smoothly and I was able to run inference on the model and obtain the labels as well as the the confidence.

However, for every other model things became very complicated. I was not getting a label anymore and I only got back a MultiArray (Float32) that (I think) contains the confidence for every different label.

 "MultiArray : Float32 1 x 58 matrix
[2.218795e-23,0,0,0,0,0,0,3.239883e-33,0,7.783418e-31,0,2.907443e-37,4.699545e-27,5.825165e-27,7.421043e-38,3.183992e-31,0,0,0,6.888631e-15,0,4.317692e-37,0,0,5.699229e-16,0,5.271491e-30,0,0,0,0,0,0,2.180327e-13,0,2.245058e-10,0,1.466715e-05,0,0,0,9.004483e-05,0,0,0,0,3.859872e-29,7.121189e-24,0.6383881,1.217046e-10,0,0,0,0,0.3615072,0,0,2.544428e-35]" (1.000000)

After experimenting a lot and always getting the same results I opened the .mlmodel in Netron and found out that the models, despite being CoreML files and trained using the same settings had different specifications.

For the first model I used these are the properties:

format: Core ML v1
type: Neural Network Classifier
input: image_0 - image<RGB,224x224>
output: (scores_0 - map<string,float64>, classLabel - string)

Properties for every other model generated in Google AutoML Vision:

format: Core ML v4
type: Neural Network
input: image_0 - float32[1,224,224,3]
output: float32

However all the model were generated the same way.

![Screen Shot 2020-09-20 at 00 26 29](https://user-images.githubusercontent.com/20358441/93691058-162ab900-fad8-11ea-9493-4e534d21ace8.png)

I want to use the CoreML models in my application but I can't figure out how to change the output type of the models. I have read the coremltools documentation and tried to implement it but I can't figure it out.  My ideia is to change the spec and load the classification labels.

Thank you!

![Screen Shot 2020-09-20 at 00 24 08](https://user-images.githubusercontent.com/20358441/93691044-a5839c80-fad7-11ea-9c52-c72c4e6759c1.png)
![Screen Shot 2020-09-20 at 00 24 17](https://user-images.githubusercontent.com/20358441/93691049-ad434100-fad7-11ea-9e99-1bd105c9ecb2.png)

**Comment by munkhuushmgl** [comment]
Where does the python code reside?

**Comment by munkhuushmgl** [comment]
Duplicate https://github.com/googleapis/python-automl/issues/73
