### ISSUE TITLE
Program hangs with call to ImageAnnotatorClient 

### ISSUE THREAD

**Issue by tataganesh** [googleapis/python-vision#523]
OS - Linux
Arch - x86_64
Machine - [Cedar cluster](https://docs.alliancecan.ca/wiki/Cedar/en) in Compute Canada
Package Version - google-cloud-vision-3.4.0

Whenever I try to initialize the client with `client = vision.ImageAnnotatorClient()`, the program seems to hang.  Performing `ctrl + c` does not work for exiting the program. I am not sure why this is happening. Making requests using the REST API works for me.  Would it be possible to get some pointers for debugging this problem?

**Comment by tataganesh** [comment]
@vpfaulkner Sorry, I don't exactly remember how I resolved this issue. I vaguely recall some problems with package version, but I am not sure.

**Comment by parthea** [comment]
I'm going to close this issue as stale but please feel free to file a new issue with more information.

If encountered this issue recently and you're using `gpcio == 1.59.0`, please see this known issue https://github.com/grpc/grpc/issues/34672 related to the recent `grpcio` release . Please use another version like `gpcio == 1.58.0` until a new release of `grpcio` is published.
https://pypi.org/project/grpcio/1.59.0/
