### ISSUE TITLE
convert api response to json

### ISSUE THREAD

**Issue by AhmadManzoor** [googleapis/python-vision#63]
accessing vision api using this code

`client = vision.ImageAnnotatorClient()
response = client.annotate_image({
  'image': {'source': {'filename': image}},
})`

response type is
`google.cloud.vision_v1.types.image_annotator.AnnotateImageResponse`

i cant convert it to json neither can iterate it

any suggestion on how t convert it to json so i can iterate it

**Comment by AhmadManzoor** [comment]
actuallly i am using annotate_image which returns all of them. i.e face_Detection, logo_detection web_detection
this returns an object of _google.cloud.vision_v1.types.image_annotator.AnnotateImageResponse_ which can be iterated for each face_Detection, logo_detection web_detection separately, 
anyways i have written a code to iterate it separately , i will share the code soon

**Comment by munkhuushmgl** [comment]
This issue has been aged. Feel free to re-open
