### ISSUE TITLE
google.api_core.exceptions.ServiceUnavailable: 503 Socket closed

### ISSUE THREAD

**Issue by vickipedia6** [googleapis/python-vision#66]
I am running 10 containers with the same credentials json which will initialize 10 imageannotatorclient. I am getting this error out of the blue recently. Should I reduce the number of client initializers? Please help. Thanks in advance.
My pip list: 

google-cloud-vision  1.0.0
google                      2.0.3
google-api-core             1.16.0
google-auth                 1.20.0
google-auth-oauthlib        0.4.1
google-cloud                0.34.0
google-cloud-core           1.4.0
google-cloud-storage        1.20.0
google-cloud-vision         1.0.0
google-pasta                0.2.0
google-resumable-media      0.4.1
googleapis-common-protos    1.6.0
grpcio                      1.30.0

@busunkim96

**Comment by vickipedia6** [comment]
Thanks for the response. Reducing the number of client vision instances seems to do the trick. However will this work around help - Retrying to instantiate the client vision instance and calling the text detection service?

**Comment by busunkim96** [comment]
Hi @vickipedia6,

There's no need to create new client objects for new method calls. If you need to _retry_ individual methods, you can pass a custom retry object to the method. 

https://googleapis.dev/python/vision/latest/vision_v1/services.html#google.cloud.vision_v1.services.product_search.ProductSearchClient.create_product
https://googleapis.dev/python/google-api-core/latest/retry.html#module-google.api_core.retry
