### ISSUE TITLE
Update README Example Usage for v2

### ISSUE THREAD

**Issue by dylancaponi** [googleapis/python-vision#67]
#### Environment details

  - OS type and version: macOS Mojave 10.14.6
  - Python version: Python 3.8.5
  - pip version: pip 20.2.3
  - google-cloud-vision version: 2.0.0

#### Steps to reproduce

  1. Run the example usage code: https://github.com/googleapis/python-vision#example-usage
  2. Get error `'google.cloud.vision' has no attribute 'enums'`

Guessing this has to do with: https://googleapis.dev/python/vision/latest/UPGRADING.html

#### Code example

```
from google.cloud import vision

client = vision.ImageAnnotatorClient()
response = client.annotate_image({
  'image': {'source': {'image_uri': 'gs://my-test-bucket/image.jpg'}},
  'features': [{'type': vision.enums.Feature.Type.FACE_DETECTION}],
})
```

#### Stack trace
```
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    'features': [{'type': vision.enums.Feature.Type.FACE_DETECTION}],
AttributeError: module 'google.cloud.vision' has no attribute 'enums'
```

**Comment by munkhuushmgl** [comment]
@dylancaponi It is due to the breaking changes https://googleapis.dev/python/vision/latest/UPGRADING.html#enums-and-types

enums and types are already moved, please refactor on your end accordingly.
