### ISSUE TITLE
How to serialize to json or dict that response from vision api?

### ISSUE THREAD

**Issue by inska** [googleapis/python-vision#70]
Hi, 

Google Cloud SDK works well to get annotation responses via vision API, and I just like to know how can I serialize the response. Is there any helper or serializer for Google response objects? Otherwise, should I parse and build dictionaries from the response object by manual?

1. OS type and version
OS X El Capitan
2. Python version and virtual environment information `python --version`
2.7.13
3. google-cloud-python version `pip show google-cloud`, `pip show google-<service>` or `pip freeze`
157.0.0
4. Stacktrace if available
5. Steps to reproduce
6. Code example

**Comment by software-dov** [comment]
All the python client libraries have been given their own repositories and no longer live under google-cloud-python. Transferring to Vision API repo.

There has been another backwards incompatible change with the Vision client library. All message types are now defined using [proto-plus](https://proto-plus-python.readthedocs.io/), which uses different methods for serialization and deserialization.

In order to get json from a message, do the following:
```python
my_message = MyMessageType(attribute=value)

json_string = MyMessageType.to_json(my_message)
# Also works
json_string = type(my_message).to_json(my_message)
# Also also works
import proto
json_string = proto.Message.to_json(my_message)
```

This is not a method on the instance but instead a class method of the metaclass.

**Comment by zyfang** [comment]
@software-dov where does MyMessageType come from?

**Comment by uditmindf007** [comment]
import proto
json_string = proto.Message.to_json(my_message)
worked for me, thanks @software-dov

**Comment by software-dov** [comment]
@zyfang It's an example type from one of the Cloud APIs.
Let's tie the example back into Vision:
```python
from google.cloud.vision import AnnotateFileRequest

request = AnnotateFileRequest()
# Do things with the fields in request.
json_string = AnnotateFileRequest.to_json(request)
```

**Comment by jaihonikhil** [comment]
I am still getting the error even after following all the above commands. Isn't there any way to extract components from "google.protobuf.pyext._message.RepeatedCompositeCo" object?

**Comment by WGribaa** [comment]
@jaihonikhil Once you get your response, you can get the wanted attribute, iterate over it and use the method `MessageToDict` on each of the elements.

It seems we now have to access the elements via their attribute "_pb" to make the method work. Here is an example :
       
    from google.protobuf.json_format import MessageToDict
    response = my_google_vision_client.label_detection(image=my_image)
    tags = response.label_annotations
    serializable_tags = [MessageToDict(tag._pb) for tag in tags]

**Comment by software-dov** [comment]
The Proto Plus documentation describes this in a more idiomatic way: https://proto-plus-python.readthedocs.io/en/stable/messages.html#serialization
The following should work:
```python
import proto
response = client.label_detection(image=my_image)
serializable_tags = [proto.Message.to_dict(tag) for tag in response.label_annotations]
```

**Comment by wenbinf** [comment]
Just in case 1) you come to this closed issue after Nov 30, 2021, and 2) try out all code snippets that you can find but still couldn't get it work...

This works for me:
   
        client = speech.SpeechClient()
        operation = client.long_running_recognize(config=config, audio=audio)
        op_result = operation.result()

        # Okay, try this:
        result_in_dict =  json.loads(type(op_result).to_json(op_result))

**Comment by Morgan-Gicheha** [comment]
This works for me
```
import proto
response = client.label_detection(image=my_image)
serializable_tags = [proto.Message.to_dict(tag) for tag in response.label_annotations]
```

**Comment by AngelDimov** [comment]
I recently ran into the same issue but I used the MessageToDict method instead:
```
from google.ads.googleads.client import GoogleAdsClient
from google.protobuf.json_format import MessageToDict

google_ads_client = GoogleAdsClient.load_from_storage(path="google-ads.yaml", version="v13")
google_ads_service = google_ads_client.get_service(name='GoogleAdsService')
search_request = google_ads_client.get_type('SearchGoogleAdsRequest')

def get_data():
        response = googleads_service.search(request=search_request) # Issues a search request
        for row in response.results:
                yield MessageToDict(row)
```

I find it a lot easier to work with the records in a dictionary format further down the line.

**Comment by AngelDimov** [comment]
I recently ran into the same issue but I used the MessageToDict method instead:
```
from google.ads.googleads.client import GoogleAdsClient
from google.protobuf.json_format import MessageToDict

google_ads_client = GoogleAdsClient.load_from_storage(path="google-ads.yaml", version="v13")
google_ads_service = google_ads_client.get_service(name='GoogleAdsService')
search_request = google_ads_client.get_type('SearchGoogleAdsRequest')

def get_data():
        response = googleads_service.search(request=search_request) # Issues a search request
        for row in response.results:
                yield MessageToDict(row)
                
for data in get_data():
        # Do something with the data                
```

I find it a lot easier to work with the records in a dictionary format further down the line.

**Comment by AngelDimov** [comment]
I recently ran into the same issue for the Google Ads API but I used the MessageToDict method instead and extended it using a generator:
```
from google.protobuf.json_format import MessageToDict

def get_data():
        response = # Make request to API
        for row in response.results:
                yield MessageToDict(row)
                
for data in get_data():
        # Do something with the data                
```

I find it a lot easier to work with the records in a dictionary format further down the line.
