### ISSUE TITLE
Error google.api_core.exceptions.InternalServerError: 500 Internal Error

### ISSUE THREAD

**Issue by seratz** [googleapis/python-vision#72]
> google-api-core 1.23.0
> grpcio 1.31.0
> google-cloud-vision 2.0.0

Hello, we are using the offline (asynchronous) batch requests to send a lot of images of old newspapers (containing a lot of text) to the Vision API using the cloud vision lib for Python 3. 

We are sending now 500 images per batch, each of those processing the `document_text` and `face_detect `features, using builtin/latest model. As we have millions of images to process, we try to send like 10 batches or more in parallel, so we look closely to our quota of "Async image annotation number of images in processing" (which for us, is currently '20,000').

The issue is, a lot of `InternalServerError: 500 Internal Error` is occurring, and the biggest problem is it seems it's not a mapped error, so Vision outputs this error, **charges against our billing and then make a retry, sometimes it works, sometimes it will give a second retry and charges us again**, so we end up with a very unpleasant billing.

Maybe it's related to LRO similar to this issue [issue ](https://github.com/googleapis/python-api-core/commit/a85533903c57be4809fe76435e298409e0903931)

#### Stack trace sample (raw)

> Traceback (most recent call last):
>   File "/code/src/job/main.py", line 47, in main
>     vision.handle()
>   File "/code/src/job/vision.py", line 386, in handle
>     result = vision.async_annotate(
>   File "/usr/lib/python3.8/site-packages/assetcloud/api/vision.py", line 246, in async_annotate
>     result = operation.result(timeout=timeout)
>   File "/usr/lib/python3.8/site-packages/google/api_core/future/polling.py", line 134, in result
>     raise self._exception
>   File "/usr/lib/python3.8/site-packages/assetcloud/api/vision.py", line 246, in async_annotate
>     result = operation.result(timeout=timeout)
>   File "/usr/lib/python3.8/site-packages/google/api_core/future/polling.py", line 134, in result
>     raise self._exception
>   File "/usr/lib/python3.8/site-packages/assetcloud/api/vision.py", line 246, in async_annotate
>     result = operation.result(timeout=timeout)
>   File "/usr/lib/python3.8/site-packages/google/api_core/future/polling.py", line 134, in result
>     raise self._exception
> google.api_core.exceptions.InternalServerError: 500 Internal Error.

Attached our python code, the abstraction and one newspaper page sample

[vision.txt](https://github.com/googleapis/python-vision/files/5517407/vision.txt)
[async_annotate.txt](https://github.com/googleapis/python-vision/files/5517408/async_annotate.txt)

![sample](https://user-images.githubusercontent.com/47662935/98677854-68e85a80-233c-11eb-97b8-36ca5f2d68c4.jpg)

**Comment by munkhuushmgl** [comment]
Thanks for bringing up this issue, looks like this might be service related bug. I will reach out internal team to find out the answer.

**Comment by munkhuushmgl** [comment]
@seratz While we are trying to log an internal bug, you can get some help on your billing issue by using the following links:

Billing support:
https://support.google.com/cloud/contact/cloud_platform_billing?visit_id=1-636564925221770723-4170709031&rd=1
Troubleshooting
https://support.google.com/cloud/troubleshooter/7279311?hl=en&ref_topic=6288636 


I will update this issue once we logged a bug.

**Comment by seratz** [comment]
@munkhuushmgl thank you Mike, I also have a ticket on gcp support regarding this issue (case 25826728). The fact is we need some urgency, because we were obligated to stop the processing of the files for our customer's project until it's fixed. Can you escalate the priority in some way?

**Comment by munkhuushmgl** [comment]
@seratz Okay, I will bring that up internally.
