### ISSUE TITLE
Asynch calls of the vision api

### ISSUE THREAD

**Issue by spoorgholi74** [googleapis/python-vision#73]
I was wondering how the calls can be made asynchronous without using the batch functionality? (with something like asyncio)

**Comment by munkhuushmgl** [comment]
There are two ways to do:
1. wrap async 
https://stackoverflow.com/questions/43241221/how-can-i-wrap-a-synchronous-function-in-an-async-coroutine
2. alternatively, you can use the recently added async client: https://github.com/googleapis/python-vision/blob/master/google/cloud/vision_v1/services/image_annotator/async_client.py

**Comment by spoorgholi74** [comment]
@munkhuushmgl 
The problem is when I use **'run_in_executor'** I get the error that :

`result = self.fn(*self.args, **self.kwargs)
TypeError: 'AnnotateImageResponse' object is not callable
`

**Comment by munkhuushmgl** [comment]
@spoorgholi74 Okay, Lemme repro this issue on my end and see if i can get the same error or not.

**Comment by munkhuushmgl** [comment]
@spoorgholi74 What are versions of your pip ?

**Comment by spoorgholi74** [comment]
> @spoorgholi74 What are versions of your pip ?

9.0.1

**Comment by munkhuushmgl** [comment]
I meant to ask all versions of APIs (vision, python3, and so on)

**Comment by spoorgholi74** [comment]
```
python                  3.6
aiohttp                  3.7.2
async-timeout            3.0.1
asyncio                  3.4.3
attrs                    20.3.0
google-api-core          1.23.0
google-auth              1.23.0
google-cloud-vision      2.0.0
googleapis-common-protos 1.52.0

```

**Comment by munkhuushmgl** [comment]
@dizcology Can u help me on this?

**Comment by dizcology** [comment]
>         response = await loop.run_in_executor(None, self.client.logo_detection(image=image))

@spoorgholi74 looks like the second parameter to `loop_run_in_executor` should be the callable function, and the arguments to that function should be passed in as the third: https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor

Could you try again and let us know if it works?

**Comment by spoorgholi74** [comment]
@dizcology Yes it worked thanks.
